services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ~/mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  web:
    build: .
    command: >
      bash -c "python manage.py migrate && 
      gunicorn dash_leaftetjs.wsgi"
    volumes:
      - .:/code
    ports:
      - "80:8000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db