# Generated by Django 4.2 on 2023-04-23 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QualidadeAr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('situacao_rede', models.CharField(max_length=10)),
                ('tipo_rede', models.CharField(max_length=5)),
                ('data', models.DateField(default=datetime.date.today)),
                ('qualidade', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255, null=True)),
                ('indice', models.IntegerField(default=0)),
                ('poluente', models.CharField(max_length=10)),
                ('municipio', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'qualidade_ar',
            },
        ),
    ]
