# Generated by Django 4.2 on 2023-04-29 01:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leaftlet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualidadear',
            name='data_atual',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
