# Generated by Django 4.2 on 2023-04-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaftlet', '0002_alter_qualidadear_indice_alter_qualidadear_poluente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualidadeardetalhes',
            name='indice',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
