name: Deploy with docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: datasaude
    steps:
      - name: building app
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 177.93.131.216
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          command_timeout: 5m
          script: |
            echo "Criando diretório"
            mkdir -p ~/app
            cd ~/app/
            echo "Clone repositório"
            [ -d dash-leftlet ] && rm -rf dash-leftlet
            git clone https://${{ secrets.GIT_USER }}:${{ secrets.GIT_TOKEN }}@github.com/cbeloni/dash-leftlet.git
            echo "Criando .env"
            cat <<EOF > dash-leftlet/.env
              SECRET_KEY= '${{ secrets.SECRET_KEY }}'
              DB_HOST=${{ secrets.DB_HOST2 }}
              DB_PORT=${{ secrets.DB_PORT2 }}
              DB_NAME=${{ secrets.DB_NAME2 }}
              DB_USER=${{ secrets.DB_USER2 }}
              DB_PASSWORD=${{ secrets.DB_PASSWORD2 }}
              DB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD2 }}
            EOF
            echo "Buildando projeto"
            cd dash-leftlet
            docker-compose up -d --no-deps --build
      - name: starting app
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 177.93.130.233
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          command_timeout: 1m
          script: |
            echo "Iniciando aplicação"
            docker-compose up -d
            echo "Aplicação em execução"